project_id = "tijrizmmdaxkgotjgwwu"

[functions.canvas-integration]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.ai-agent]
verify_jwt = false

[functions.weekly-digest]
verify_jwt = false
